apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: p2-frontend
          image: ghcr.io/tanthana48/p2-frontend/p2-frontend:latest
      imagePullSecrets:
        - name: regcred
